services:
  file-upload:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/uploads
      - ./src:/app  # 将本地源代码挂载到容器中，便于开发时实时更新
      - ./tests:/tests  # 将测试目录挂载到容器中，便于开发时运行测试
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped